list(APPEND blusys_sources
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/adc.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/dac.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/efuse.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/error.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/gpio.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/gpio_expander.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/i2c.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/i2c_slave.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/i2s.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/i2s_rx.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/mcpwm.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/nvs.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/one_wire.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/pcnt.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/pwm.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/rmt.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/rmt_rx.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/sd_spi.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/sdm.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/sdmmc.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/sleep.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/spi.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/spi_slave.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/system.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/target.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/temp_sensor.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/timer.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/touch.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/twai.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/uart.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/usb_device.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/usb_host.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/version.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/wdt.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/internal/bt_stack.c
    ${BLUSYS_COMPONENT_SRC_DIR}/hal/internal/lock_freertos.c
)
