#pragma once

#include "blusys/framework/capabilities/capability.hpp"
#include "blusys/framework/capabilities/event.hpp"
#include "blusys/framework/capabilities/list.hpp"
#include "blusys/framework/capabilities/connectivity.hpp"
#include "blusys/framework/capabilities/storage.hpp"
#include "blusys/framework/capabilities/bluetooth.hpp"
#include "blusys/framework/capabilities/ble_hid_device.hpp"
#include "blusys/framework/capabilities/mqtt.hpp"
#include "blusys/framework/capabilities/ota.hpp"
#include "blusys/framework/capabilities/build_info.hpp"
#include "blusys/framework/capabilities/diagnostics.hpp"
#include "blusys/framework/capabilities/telemetry.hpp"
#include "blusys/framework/capabilities/lan_control.hpp"
#include "blusys/framework/capabilities/usb.hpp"
#include "blusys/framework/capabilities/persistence.hpp"
