#ifndef BLUSYS_MQTT_H
#define BLUSYS_MQTT_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "blusys/hal/error.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct blusys_mqtt blusys_mqtt_t;

typedef enum {
    BLUSYS_MQTT_QOS_0 = 0,
    BLUSYS_MQTT_QOS_1 = 1,
    BLUSYS_MQTT_QOS_2 = 2,
} blusys_mqtt_qos_t;

/* Called from the MQTT client task when a message arrives on a subscribed topic.
   topic is null-terminated.  payload is raw bytes and is NOT null-terminated;
   use payload_len to determine length. */
typedef void (*blusys_mqtt_message_cb_t)(const char    *topic,
                                         const uint8_t *payload,
                                         size_t         payload_len,
                                         void          *user_ctx);

/* Transport state transitions surfaced to higher layers. Delivered from
   the MQTT client task — treat like an ISR: no blocking work, just latch
   a flag or post to your own queue. */
typedef enum {
    BLUSYS_MQTT_STATE_CONNECTED    = 0,
    BLUSYS_MQTT_STATE_DISCONNECTED = 1,
    BLUSYS_MQTT_STATE_ERROR        = 2,
} blusys_mqtt_state_t;

typedef void (*blusys_mqtt_state_cb_t)(blusys_mqtt_state_t state, void *user_ctx);

typedef struct {
    const char               *broker_url;     /* required; e.g. "mqtt://broker.example.com:1883" */
    const char               *username;        /* NULL = no authentication */
    const char               *password;        /* NULL = no authentication */
    const char               *client_id;       /* NULL = auto-generated by ESP-IDF */
    const char               *server_cert_pem; /* PEM CA cert for MQTTS; NULL skips verification */
    int                       timeout_ms;      /* connect timeout; BLUSYS_TIMEOUT_FOREVER to block */
    blusys_mqtt_message_cb_t  message_cb;      /* called on incoming messages; NULL = no subscription handling */
    blusys_mqtt_state_cb_t    state_cb;        /* called on connected/disconnected/error; NULL = none */
    void                     *user_ctx;        /* passed through to message_cb and state_cb */

    /* Optional MQTT Last-Will-and-Testament. Broker publishes this on
       ungraceful disconnect. `will_topic == NULL` disables LWT. */
    const char               *will_topic;       /* NULL = no LWT */
    const char               *will_payload;     /* may be NULL or empty */
    size_t                    will_payload_len; /* 0 → strlen(will_payload) if non-NULL, else 0 */
    blusys_mqtt_qos_t         will_qos;         /* ignored when will_topic == NULL */
    bool                      will_retain;      /* ignored when will_topic == NULL */
} blusys_mqtt_config_t;

/* Allocate and initialise an MQTT client.  Does not connect to the broker.
   Returns BLUSYS_ERR_INVALID_ARG if config or out_handle is NULL, broker_url is NULL,
   or timeout_ms is invalid (less than BLUSYS_TIMEOUT_FOREVER).
   Returns BLUSYS_ERR_NO_MEM on allocation failure.
   Returns BLUSYS_ERR_NOT_SUPPORTED on targets without WiFi. */
blusys_err_t blusys_mqtt_open(const blusys_mqtt_config_t *config, blusys_mqtt_t **out_handle);

/* Release all resources.  Disconnects first if still connected. */
blusys_err_t blusys_mqtt_close(blusys_mqtt_t *handle);

/* Connect to the broker.  Blocks until CONNACK is received, the timeout expires,
   or a network error occurs.
   Returns BLUSYS_ERR_TIMEOUT if the broker did not respond within timeout_ms.
   Returns BLUSYS_ERR_IO on network-level failure. */
blusys_err_t blusys_mqtt_connect(blusys_mqtt_t *handle);

/* Disconnect from the broker. */
blusys_err_t blusys_mqtt_disconnect(blusys_mqtt_t *handle);

/* Publish a message.  Fire-and-forget: QoS acknowledgments are handled by the
   ESP-IDF MQTT stack and are not surfaced here.  When retain is true the
   broker stores the message as the latest retained payload on that topic.
   Returns BLUSYS_ERR_INVALID_STATE if not connected. */
blusys_err_t blusys_mqtt_publish(blusys_mqtt_t *handle,
                                  const char    *topic,
                                  const uint8_t *payload,
                                  size_t         payload_len,
                                  blusys_mqtt_qos_t qos,
                                  bool           retain);

/* Subscribe to a topic filter.  Incoming messages are delivered via the message_cb
   set at open time.
   Returns BLUSYS_ERR_INVALID_STATE if not connected. */
blusys_err_t blusys_mqtt_subscribe(blusys_mqtt_t *handle,
                                    const char    *topic,
                                    blusys_mqtt_qos_t qos);

/* Unsubscribe from a topic filter.
   Returns BLUSYS_ERR_INVALID_STATE if not connected. */
blusys_err_t blusys_mqtt_unsubscribe(blusys_mqtt_t *handle, const char *topic);

/* Returns true if the client is currently connected to the broker. */
bool blusys_mqtt_is_connected(blusys_mqtt_t *handle);

#ifdef __cplusplus
}
#endif

#endif
