#ifndef BLUSYS_TARGET_CAPS_H
#define BLUSYS_TARGET_CAPS_H

#include <stdint.h>

#include "blusys/target.h"

#define BLUSYS_FEATURE_MASK(feature) (1ull << (unsigned) (feature))

#define BLUSYS_BASE_FEATURE_MASK \
    (BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_GPIO) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_UART) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2C) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2S) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SPI) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_PWM) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_ADC) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TIMER) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_RMT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TWAI) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WDT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SLEEP) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SDM) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2C_SLAVE) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SPI_SLAVE) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2S_RX) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_RMT_RX) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WIFI) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_NVS) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_CLIENT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MQTT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_SERVER) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_OTA) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SNTP) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MDNS) | \
     BLUSYS_BLUETOOTH_FEATURE_MASK | \
     BLUSYS_FS_FEATURE_MASK | \
     BLUSYS_ESPNOW_FEATURE_MASK | \
     BLUSYS_BLE_GATT_FEATURE_MASK | \
     BLUSYS_BUTTON_FEATURE_MASK | \
     BLUSYS_LED_STRIP_FEATURE_MASK | \
     BLUSYS_CONSOLE_FEATURE_MASK | \
     BLUSYS_FATFS_FEATURE_MASK | \
     BLUSYS_SD_SPI_FEATURE_MASK | \
     BLUSYS_POWER_MGMT_FEATURE_MASK | \
     BLUSYS_WS_CLIENT_FEATURE_MASK | \
     BLUSYS_WIFI_PROV_FEATURE_MASK | \
     BLUSYS_LCD_FEATURE_MASK | \
     BLUSYS_ENCODER_FEATURE_MASK | \
     BLUSYS_BUZZER_FEATURE_MASK | \
     BLUSYS_ONE_WIRE_FEATURE_MASK | \
     BLUSYS_SEVEN_SEG_FEATURE_MASK | \
     BLUSYS_DHT_FEATURE_MASK | \
     BLUSYS_USB_HID_FEATURE_MASK)

#define BLUSYS_NVS_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_NVS)
#define BLUSYS_PCNT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_PCNT)
#define BLUSYS_TOUCH_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TOUCH)
#define BLUSYS_DAC_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_DAC)
#define BLUSYS_SDMMC_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SDMMC)
#define BLUSYS_TEMP_SENSOR_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TEMP_SENSOR)
#define BLUSYS_WDT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WDT)
#define BLUSYS_SLEEP_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SLEEP)
#define BLUSYS_MCPWM_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MCPWM)
#define BLUSYS_HTTP_CLIENT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_CLIENT)
#define BLUSYS_MQTT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MQTT)
#define BLUSYS_HTTP_SERVER_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_SERVER)
#define BLUSYS_OTA_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_OTA)
#define BLUSYS_SNTP_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SNTP)
#define BLUSYS_MDNS_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MDNS)
#define BLUSYS_BLUETOOTH_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_BLUETOOTH)
#define BLUSYS_FS_FEATURE_MASK        BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_FS)
#define BLUSYS_ESPNOW_FEATURE_MASK    BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_ESPNOW)
#define BLUSYS_BLE_GATT_FEATURE_MASK  BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_BLE_GATT)
#define BLUSYS_BUTTON_FEATURE_MASK    BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_BUTTON)
#define BLUSYS_LED_STRIP_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_LED_STRIP)
#define BLUSYS_CONSOLE_FEATURE_MASK   BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_CONSOLE)
#define BLUSYS_FATFS_FEATURE_MASK     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_FATFS)
#define BLUSYS_SD_SPI_FEATURE_MASK      BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SD_SPI)
#define BLUSYS_POWER_MGMT_FEATURE_MASK  BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_POWER_MGMT)
#define BLUSYS_WS_CLIENT_FEATURE_MASK   BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WS_CLIENT)
#define BLUSYS_WIFI_PROV_FEATURE_MASK   BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WIFI_PROV)
#define BLUSYS_LCD_FEATURE_MASK         BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_LCD)
#define BLUSYS_ENCODER_FEATURE_MASK     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_ENCODER)
#define BLUSYS_BUZZER_FEATURE_MASK      BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_BUZZER)
#define BLUSYS_ONE_WIRE_FEATURE_MASK    BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_ONE_WIRE)
#define BLUSYS_SEVEN_SEG_FEATURE_MASK   BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SEVEN_SEG)
#define BLUSYS_DHT_FEATURE_MASK         BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_DHT)
#define BLUSYS_USB_HOST_FEATURE_MASK    BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_USB_HOST)
#define BLUSYS_USB_DEVICE_FEATURE_MASK  BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_USB_DEVICE)
#define BLUSYS_USB_HID_FEATURE_MASK     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_USB_HID)

typedef struct {
    blusys_target_t target;
    const char *name;
    uint8_t cpu_cores;
    uint64_t feature_mask;
} blusys_target_caps_t;

const blusys_target_caps_t *blusys_target_caps_get(void);

#endif
