#!/usr/bin/env python3
"""
Provision an ESP32 device against an Atlas deployment and flash the
blusys Atlas example firmware.

Self-contained: talks to the Atlas REST API over HTTP, fetches the CA
from `GET /infra/ca.crt`, renders `main/include/atlas_config.h` and
`main/include/ca_cert.h`, then invokes `idf.py` in this example's
directory.

Requires: Python 3.8+, a sourced ESP-IDF environment (`. export.sh`).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

EXAMPLE_DIR = Path(__file__).resolve().parent.parent
INCLUDE_DIR = EXAMPLE_DIR / "main" / "include"
TEMPLATE_PATH = INCLUDE_DIR / "atlas_config.h.template"
CONFIG_PATH = INCLUDE_DIR / "atlas_config.h"
CA_PATH = INCLUDE_DIR / "ca_cert.h"

TARGETS = ("esp32", "esp32c3", "esp32s3")


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def http_json(method: str, url: str, token: str | None = None,
              body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body is not None else None
    headers = {"Content-Type": "application/json"} if data else {}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        err_body = e.read().decode(errors="replace")
        die(f"{method} {url} -> {e.code}: {err_body}")
    except urllib.error.URLError as e:
        die(f"{method} {url} failed: {e.reason}")


def http_text(url: str) -> str:
    try:
        with urllib.request.urlopen(url, timeout=15) as resp:
            return resp.read().decode()
    except urllib.error.HTTPError as e:
        die(f"GET {url} -> {e.code}: {e.read().decode(errors='replace')}")
    except urllib.error.URLError as e:
        die(f"GET {url} failed: {e.reason}")


def render_ca_header(pem: str) -> str:
    lines = [ln.rstrip() for ln in pem.strip().splitlines()]
    body = " \\\n".join(f'  "{ln}\\n"' for ln in lines)
    return (
        "// Auto-generated by tools/provision.py — do not edit.\n"
        "#pragma once\n\n"
        "#define CA_CERT \\\n"
        f"{body}\n"
    )


def render_config(template: str, values: dict[str, str]) -> str:
    def sub(match: re.Match[str]) -> str:
        key = match.group(1)
        if key not in values:
            die(f"template references unknown placeholder @@{key}@@")
        return values[key]
    return re.sub(r"@@(\w+)@@", sub, template)


def run(cmd: list[str], cwd: Path) -> None:
    print(f"$ {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=cwd)
    if result.returncode != 0:
        die(f"command failed: {' '.join(cmd)}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--atlas-url", default=os.getenv("ATLAS_API_URL", "http://localhost:3000"))
    p.add_argument("--admin-email", default=os.getenv("ATLAS_ADMIN_EMAIL", "admin@atlas.local"))
    p.add_argument("--admin-password", default=os.getenv("ATLAS_ADMIN_PASSWORD"))
    p.add_argument("--admin-token", default=os.getenv("ATLAS_ADMIN_TOKEN"))
    p.add_argument("--name", required=True, help="Device name to register")
    p.add_argument("--target", required=True, choices=TARGETS)
    p.add_argument("--wifi-ssid", required=True)
    p.add_argument("--wifi-pass", required=True)
    p.add_argument("--mqtt-host", required=True, help="Broker hostname / IP reachable by the device")
    p.add_argument("--mqtt-port", default="8883")
    p.add_argument("--port", help="Serial port for flashing (default: idf.py autodetect)")
    p.add_argument("--skip-flash", action="store_true", help="Render config and build, but do not flash")
    p.add_argument("--device-type", default="esp32", help="Atlas device type (default: esp32)")
    args = p.parse_args()

    if not TEMPLATE_PATH.is_file():
        die(f"template not found: {TEMPLATE_PATH}")
    if not args.admin_token and not args.admin_password:
        die("provide --admin-password or --admin-token (or ATLAS_ADMIN_PASSWORD env)")

    print("=== Atlas provisioning (blusys) ===")
    print(f"Atlas API   : {args.atlas_url}")
    print(f"Device name : {args.name}")
    print(f"Target      : {args.target}")
    print(f"MQTT broker : {args.mqtt_host}:{args.mqtt_port}")
    print()

    token = args.admin_token
    if not token:
        print("[1/5] Logging in to Atlas...")
        resp = http_json("POST", f"{args.atlas_url}/auth/login",
                         body={"email": args.admin_email, "password": args.admin_password})
        token = resp.get("access_token")
        if not token:
            die(f"login response missing access_token: {resp}")
        print("  login OK")
    else:
        print("[1/5] Using provided admin token")

    print("[2/5] Registering device...")
    reg = http_json("POST", f"{args.atlas_url}/devices", token=token,
                    body={"name": args.name, "type": args.device_type})
    device_id = reg.get("id")
    mqtt_token = reg.get("mqttToken")
    if not device_id or not mqtt_token:
        die(f"device registration missing id/mqttToken: {reg}")
    print(f"  device id   : {device_id}")
    print(f"  mqtt token  : {mqtt_token[:8]}... (shown once)")

    print("[3/5] Fetching CA from Atlas...")
    pem = http_text(f"{args.atlas_url}/infra/ca.crt")
    if "BEGIN CERTIFICATE" not in pem:
        die(f"/infra/ca.crt did not return PEM: {pem[:200]}")
    CA_PATH.write_text(render_ca_header(pem))
    print(f"  wrote {CA_PATH}")

    print("[4/5] Rendering atlas_config.h...")
    template = TEMPLATE_PATH.read_text()
    config = render_config(template, {
        "DEVICE_ID": device_id,
        "MQTT_TOKEN": mqtt_token,
        "WIFI_SSID": args.wifi_ssid,
        "WIFI_PASS": args.wifi_pass,
        "MQTT_HOST": args.mqtt_host,
        "MQTT_PORT": args.mqtt_port,
    })
    CONFIG_PATH.write_text(config)
    print(f"  wrote {CONFIG_PATH}")

    print(f"[5/5] Building{' (flash skipped)' if args.skip_flash else ' + flashing'}...")
    if not os.environ.get("IDF_PATH"):
        die("IDF_PATH not set — source ESP-IDF export.sh before running")
    run(["idf.py", "set-target", args.target], cwd=EXAMPLE_DIR)
    if args.skip_flash:
        run(["idf.py", "build"], cwd=EXAMPLE_DIR)
    else:
        flash_cmd = ["idf.py"]
        if args.port:
            flash_cmd += ["-p", args.port]
        flash_cmd += ["flash"]
        run(flash_cmd, cwd=EXAMPLE_DIR)

    print()
    print("=== Provisioning complete ===")
    print(f"Device ID  : {device_id}")
    print(f"MQTT token : {mqtt_token[:8]}... (save — shown only once)")
    print(f"Monitor    : idf.py -C {EXAMPLE_DIR} monitor")
    return 0


if __name__ == "__main__":
    sys.exit(main())
