#ifndef BLUSYS_TARGET_CAPS_H
#define BLUSYS_TARGET_CAPS_H

#include <stdint.h>

#include "blusys/target.h"

#define BLUSYS_FEATURE_MASK(feature) (1u << (unsigned) (feature))

#define BLUSYS_BASE_FEATURE_MASK \
    (BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_GPIO) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_UART) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2C) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2S) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SPI) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_PWM) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_ADC) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TIMER) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_RMT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TWAI) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WDT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SLEEP) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SDM) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2C_SLAVE) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SPI_SLAVE) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_I2S_RX) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_RMT_RX) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WIFI) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_NVS) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_CLIENT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MQTT) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_SERVER) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_OTA) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SNTP) | \
     BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MDNS))

#define BLUSYS_NVS_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_NVS)
#define BLUSYS_PCNT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_PCNT)
#define BLUSYS_TOUCH_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TOUCH)
#define BLUSYS_DAC_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_DAC)
#define BLUSYS_SDMMC_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SDMMC)
#define BLUSYS_TEMP_SENSOR_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_TEMP_SENSOR)
#define BLUSYS_WDT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_WDT)
#define BLUSYS_SLEEP_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SLEEP)
#define BLUSYS_MCPWM_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MCPWM)
#define BLUSYS_HTTP_CLIENT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_CLIENT)
#define BLUSYS_MQTT_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MQTT)
#define BLUSYS_HTTP_SERVER_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_HTTP_SERVER)
#define BLUSYS_OTA_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_OTA)
#define BLUSYS_SNTP_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_SNTP)
#define BLUSYS_MDNS_FEATURE_MASK BLUSYS_FEATURE_MASK(BLUSYS_FEATURE_MDNS)

typedef struct {
    blusys_target_t target;
    const char *name;
    uint8_t cpu_cores;
    uint32_t feature_mask;
} blusys_target_caps_t;

const blusys_target_caps_t *blusys_target_caps_get(void);

#endif
