#pragma once

// Umbrella include for the stock widget kit (primitives + interactive + display widgets).

#include "blusys/framework/ui/callbacks.hpp"
#include "blusys/framework/ui/input/encoder.hpp"
#include "blusys/framework/ui/primitives.hpp"
#include "blusys/framework/ui/theme.hpp"
#include "blusys/framework/ui/widgets/button/button.hpp"
#include "blusys/framework/ui/widgets/card/card.hpp"
#include "blusys/framework/ui/widgets/chart/chart.hpp"
#include "blusys/framework/ui/widgets/data_table/data_table.hpp"
#include "blusys/framework/ui/widgets/dropdown/dropdown.hpp"
#include "blusys/framework/ui/widgets/gauge/gauge.hpp"
#include "blusys/framework/ui/widgets/input_field/input_field.hpp"
#include "blusys/framework/ui/widgets/knob/knob.hpp"
#include "blusys/framework/ui/widgets/level_bar/level_bar.hpp"
#include "blusys/framework/ui/widgets/list/list.hpp"
#include "blusys/framework/ui/widgets/modal/modal.hpp"
#include "blusys/framework/ui/widgets/overlay/overlay.hpp"
#include "blusys/framework/ui/widgets/progress/progress.hpp"
#include "blusys/framework/ui/widgets/slider/slider.hpp"
#include "blusys/framework/ui/widgets/tabs/tabs.hpp"
#include "blusys/framework/ui/widgets/toggle/toggle.hpp"
#include "blusys/framework/ui/widgets/vu_strip/vu_strip.hpp"
