#!/usr/bin/env bash
# Scaffold a new capability header plus host/device implementations.
#
# Usage:
#   ./scripts/scaffold/new-capability.sh <name> [component-root]
#
# The target root defaults to the current directory and should be the root of a
# Blusys-style component tree (with include/ and src/ siblings).

set -euo pipefail

usage() {
    printf 'Usage: %s <name> [component-root]\n' "$0" >&2
    exit 2
}

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    usage
fi

capability_name="$1"
component_root="${2:-.}"

python3 - "$capability_name" "$component_root" <<'PY'
from __future__ import annotations

import re
import sys
from pathlib import Path

name = sys.argv[1].strip()
root = Path(sys.argv[2]).resolve()

if not re.fullmatch(r"[a-z][a-z0-9_]*", name):
    raise SystemExit("error: capability name must match [a-z][a-z0-9_]*")

cap_dir = root / "include" / "blusys" / "framework" / "capabilities"
src_dir = root / "src" / "framework" / "capabilities"
cap_dir.mkdir(parents=True, exist_ok=True)
src_dir.mkdir(parents=True, exist_ok=True)

header_path = cap_dir / f"{name}.hpp"
host_path = src_dir / f"{name}_host.cpp"
device_path = src_dir / f"{name}_device.cpp"

for path in (header_path, host_path, device_path):
    if path.exists():
        raise SystemExit(f"error: {path} already exists")

class_name = f"{name}_capability"
config_name = f"{name}_config"
status_name = f"{name}_status"

header = f'''#pragma once

// Capability scaffold generated by scripts/scaffold/new-capability.sh.
// Update capability_kind::custom to a dedicated enum entry before shipping.

#include "blusys/framework/capabilities/capability.hpp"

#include <cstdint>

namespace blusys {{

struct {config_name} {{
    std::uint32_t sample_interval_ms = 1000;
}};

struct {status_name} : capability_status_base {{
    std::int32_t last_value = 0;
    std::uint32_t sample_count = 0;
}};

class {class_name} final : public capability_base {{
public:
    static constexpr capability_kind kind_value = capability_kind::custom;

    explicit {class_name}(const {config_name} &cfg);
    ~{class_name}() override;

    [[nodiscard]] capability_kind kind() const override {{ return kind_value; }}

    blusys_err_t start(blusys::runtime &rt) override;
    void poll(std::uint32_t now_ms) override;
    void stop() override;

    [[nodiscard]] const {status_name} &status() const {{ return status_; }}

    blusys_err_t read(std::int32_t *out);

private:
    {config_name} cfg_;
    {status_name} status_{{}};
    std::uint32_t last_sample_ms_ = 0;
}};

}}  // namespace blusys
'''

impl = f'''#include "blusys/framework/capabilities/{name}.hpp"

namespace blusys {{

{class_name}::{class_name}(const {config_name} &cfg)
    : cfg_(cfg)
{{
}}

{class_name}::~{class_name}() = default;

blusys_err_t {class_name}::start(runtime &rt)
{{
    rt_ = &rt;
    status_.capability_ready = true;
    status_.last_value       = 0;
    status_.sample_count     = 0;
    last_sample_ms_          = 0;
    return BLUSYS_OK;
}}

void {class_name}::poll(std::uint32_t now_ms)
{{
    if ((now_ms - last_sample_ms_) < cfg_.sample_interval_ms) {{
        return;
    }}
    last_sample_ms_        = now_ms;
    status_.last_value     = static_cast<std::int32_t>(status_.sample_count);
    status_.sample_count  += 1;
}}

void {class_name}::stop()
{{
    status_.capability_ready = false;
    rt_ = nullptr;
}}

blusys_err_t {class_name}::read(std::int32_t *out)
{{
    if (out == nullptr) {{
        return BLUSYS_ERR_INVALID_ARG;
    }}
    *out = status_.last_value;
    return BLUSYS_OK;
}}

}}  // namespace blusys
'''

header_path.write_text(header, encoding="utf-8")
host_path.write_text(
    "// Host scaffold implementation mirrors the device shape.\n" + impl,
    encoding="utf-8",
)
device_path.write_text(
    "// Device scaffold implementation mirrors the host shape.\n" + impl,
    encoding="utf-8",
)

print(f"scaffolded capability: {name}")
print(f"  {header_path}")
print(f"  {host_path}")
print(f"  {device_path}")
PY
